apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:

      containers:
      - name: nginxcontainers
        image: nginx:trixie-perl
        ports:
        - containerPort: 80

        env:
        - name: name
          valueFrom:
            configMapKeyRef:
              name: cm
              key: name

        - name: sc
          valueFrom:
            secretKeyRef:
              name: ms
              key: pass

      tolerations:
      - key: "app"
        value: "nginx"
        effect: "NoSchedule"

      nodeSelector:
        size: mid

      resources:
        requests:
          cpu: 1
          memory: "1Gi"

        limits:
          memory: "2Gi"
          cpu: 2
